# Adapted from https://github.com/alshedivat/al-folio/blob/master/.github/workflows/prettier-comment-on-pr.yml
name: Comment on pull request

on:
  repository_dispatch:
    types: [prettier-failed-on-pr]

jobs:
  comment:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: PR comment with html diff 💬
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: prettier-failed
          pr_number: ${{ github.event.client_payload.pr_number }}
          message: |
            [Verificação de formatação do Prettier](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.client_payload.run_id }}) falhou. Verifique [esse arquivo](${{ github.event.client_payload.artifact_url }}) para mais informações.
